# Generated by Django 4.1.1 on 2023-01-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='insight',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
