# Generated by Django 4.1.5 on 2023-05-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_customuser_email_verification_customuser_native_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='native_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_no',
            new_name='city',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
