# Generated by Django 4.1.5 on 2023-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_deliverydetails_user_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased',
            name='user',
        ),
        migrations.AddField(
            model_name='purchased',
            name='email',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='purchased',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='reference',
            field=models.CharField(max_length=400, null=True, unique=True),
        ),
    ]
