# Generated by Django 4.1.5 on 2023-05-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_purchased_user_purchased_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, null=True)),
                ('total', models.BigIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('process', 'processing'), ('transit', 'on transit'), ('delivered', 'delivered')], default='process', max_length=50)),
                ('transaction_id', models.CharField(max_length=300, null=True)),
                ('tracking_id', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.DeleteModel(
            name='Purchased',
        ),
        migrations.AddField(
            model_name='purchaseditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
