# Generated by Django 4.1.5 on 2023-05-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_purchaseditem_remove_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='address',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='deliverydetails',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaseditem',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'processing'), ('on_transit', 'on_transit'), ('delivered', 'delivered')], default='processing', max_length=50),
        ),
    ]
