# Generated by Django 4.1.5 on 2023-05-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_purchaseditem_address_alter_deliverydetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
