# Generated by Django 4.1.5 on 2023-05-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_purchaseditem_city_purchaseditem_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseditem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='purchaseditem',
            name='country',
        ),
        migrations.RemoveField(
            model_name='purchaseditem',
            name='state',
        ),
    ]
